### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getId' of null

### ISSUE THREAD

**Issue by laughedelic** [benjaminRomano/bottom-dock#1]
[Enter steps to reproduce below:]

I had a TODO panel open and just clicked `x` close button.

**Atom Version**: 1.0.3
**System**: Mac OS X 10.10.5
**Thrown From**: [bottom-dock](https://github.com/benjaminRomano/bottom-dock) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getId' of null

```
At /Users/laughedelic/.atom/packages/bottom-dock/lib/views/dock-pane-manager.coffee:55

TypeError: Cannot read property 'getId' of null
  at DockPaneManager.deletePane (/Users/laughedelic/.atom/packages/bottom-dock/lib/views/dock-pane-manager.coffee:55:17)
  at BottomDock.deletePane (/Users/laughedelic/.atom/packages/bottom-dock/lib/views/bottom-dock.coffee:49:32)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TabManager.deleteClicked (/Users/laughedelic/.atom/packages/bottom-dock/lib/views/tab-manager.coffee:57:16)
  at TabManager.deleteClicked (/Users/laughedelic/.atom/packages/bottom-dock/lib/views/tab-manager.coffee:1:1)
  at HTMLSpanElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
  at HTMLSpanElement.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLSpanElement.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

**Comment by benjaminRomano** [comment]
This was a problem with the todo-manager package. I fixed it in this commit, https://github.com/benjaminRomano/todo-manager/commit/d2f096637f67668006503dc300c2b6c66f3b4918.
