### ISSUE TITLE
Failed to activate the bottom-dock package

### ISSUE THREAD

**Issue by Northseastorm** [benjaminRomano/bottom-dock#19]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro N
**Thrown From**: [bottom-dock](https://github.com/benjaminRomano/bottom-dock) package 0.4.4

### Stack Trace

Failed to activate the bottom-dock package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/bottom-dock/lib/views/bottom-dock.coffee:2:10)
    at /packages/bottom-dock/lib/views/bottom-dock.coffee:1:1)
    at /packages/bottom-dock/lib/views/bottom-dock.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:146745)
    at /packages/bottom-dock/lib/main.coffee:5:14)
    at /packages/bottom-dock/lib/main.coffee:1:1)
    at /packages/bottom-dock/lib/main.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:721712)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3338526)
    at Package.activateNow (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326510)
    at measure (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326288)
    at Package.measure (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3323898)
    at activationPromise.activationPromise.Promise (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326148)
    at new Promise (<anonymous>)
    at Package.activate (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:3326091)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:382452)
    at config.transactAsync (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:382068)
    at Config.transactAsync (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:331716)
    at PackageManager.activatePackages (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:382018)
    at PackageManager.activate (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:381568)
    at t.loadState.then (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:1:743877)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
atom-minify 0.8.0 
atom-sort-sass 0.2.1 
atom-wrap-in-tag 0.6.0 
autocomplete-font-awesome 1.0.2 
autocomplete-paths 2.12.2 
bottom-dock 0.4.4 
drunken-php 0.2.4 
emmet 2.4.3 
file-icons 2.1.40 
gulp-manager 0.2.19 
highlight-selected 0.17.0 
html-to-css 0.2.2 
ide-css 0.3.4 
open-terminal-here 2.3.2 
php-cs-fixer 4.1.1 
pigments 0.40.2 
remote-ftp 2.2.4 
Sublime-Style-Column-Selection 1.7.5 
sync-settings 4.3.2 
```

**Comment by benjaminRomano** [comment]
Hey @Northseastorm these packages are long since deprecated. I haven't made updates to this in years
